sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: VJYJL/9XhX+pYfEFIPbCLhd3qiuidIIZqydMKFZ2nTzgzLAlQVjg6Ur0mESGboXfKQQOmKZdAzwZnGgr+otgR0xNZmMd+Uy2SH1yLPfyemXdzNdYkk1r2R1ZR0lZL4/LLtBrQ6Jqd+XaO+56JKriu3uz25/xGol0n8rRs/wQrTOabHGJkpbWVNNoXlmvICHyP5W0aYx1q/unmZAWqgAND8Ectkb43X06OdSBdyDOVS9FvW4U+QkMN9utVxFHoLhXVWEvvF0yWOFZzjhDidNYZfEQoRBbSp+x8+8zM7NhDFrzAKmXHiut2H9kt4/uqwNsL5sM0pTwGqR2KriiWlQyOjKorlaTQPGacf5LEwdcIkVK9UN1skq3M97kecSXCR1iDoZm+3WraVXLaC8vrZDL+xRJUKeI0YKBC8anVLaROb/cZ1N/UsCs7JYEK7B9vwQjU9A6Z6Wlxl9QocRPOj8XLk3OIPE++Qb+HzrJrn8p5oh1kusxZhkDNPjJdjDwTrCulIO3jZy6dnaw51uUgXc+oZIaerUZwA3sVW4hEXEYWswzWlWfby0/YJUCl7ZCTj1teVhmaic036u8MffN99D43DqRw/OVq8qVSi2AsKHRa4rVnxChD/Kn84zRt2o+n+Bl/QkbRrHF1zmKa0PzjOl/LD8N0yz29mKUcpHPPKlHWuo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Wars-of-the-Jews--Or-The-History-of-the-Destruction-of-Jerusalem_2850
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy